### ISSUE TITLE
Incomplete import of 70 LY xlsx dataset 

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#249]
When you import the 70 ly dataset, it imports 3423 stars, but there are 3434 lines in the excel spreadsheet other than the headings. 

The following appears in the log during import 11 times (thus, the number of stars missing.  Note that despite what it says, there are NO lines with blank spectral classes OR orthospec. 

```
2021-03-12 06:52:15.987  INFO 14624 --- [lication Thread] c.t.t.d.dataset.DataSetManagerDialog     : loaded data set dialog
java.lang.NullPointerException: Cannot invoke "com.teamgannon.trips.stellarmodelling.StellarClassification.getStellarType()" because "stellarClassification" is null
        at com.teamgannon.trips.stellarmodelling.StarModel.setStarClass(StarModel.java:52)
        at com.teamgannon.trips.stellarmodelling.StarCreator.parseSpectral(StarCreator.java:57)
        at com.teamgannon.trips.jpa.model.StarObject.calculateBaseScore(StarObject.java:642)
        at com.teamgannon.trips.jpa.model.StarObject.calculateDisplayScore(StarObject.java:515)
        at com.teamgannon.trips.file.csvin.model.AstroCSVStar.toAstrographicObject(AstroCSVStar.java:252)
        at com.teamgannon.trips.file.excel.normal.ExcelReader.useStreamingAPI(ExcelReader.java:108)
        at com.teamgannon.trips.file.excel.normal.ExcelReader.loadFile(ExcelReader.java:48)
        at com.teamgannon.trips.service.importservices.tasks.ExcelLoadTask.call(ExcelLoadTask.java:39)
        at com.teamgannon.trips.service.importservices.tasks.ExcelLoadTask.call(ExcelLoadTask.java:15)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ljramones** [comment]
Figured out the issue.
I put checks in for a null and then I saw what the value actually was

You have a 0 (zero) and not a O as the spectral class for those incorrect spectral values.
I'll do a quick fix to change it to a O instead of 0

**Comment by ljramones** [comment]
Also in the TRIPS-normal-names-70 excel file the star "LP-666-9 has a malformed line

> line before ---
E901FB5E-C126-0E43-98D1-0CF0BF8372D2 | 70LY | AP Colum |   | @866365 | Gaia DR2 2886233695250041216\|N | Columba | 0 | 0 | 0 | Simbad\|GaiaDR2 | ...

> offending line ---
91471680-AC5B-B946-BA75-870352C3CF55 | 70LY | LP 666-9 |   | @1138634 | Gaia DR2 5761985432616501376 | Hydra | 0 | 0 |   | Simbad\|GaiaDR2 | ...

note the missing " | 0 | 0 |   |" value coopered to the line above " | 0 | 0 | 0 | "
somehow that causes the excel reader to be off by one.

**Comment by ljramones** [comment]
same thing with 

57C0D8DD-5E5E-6040-8C91-597402CF4AB8 | 70LY | HD 223778 |   | @252807 | Gaia DR2 2232348941892509184 | Cepheus | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

the " | 0 | 0 |   |" seems to mess up the excel reader

**Comment by ljramones** [comment]
again


4CE537C9-9C04-CE41-AA64-039959747CB3 | 70LY | HD 188088 |   | @2506383 | Gaia DR2 6863535898551993472 | Sagittar | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
another


6DB0FB3E-2C03-BD46-9146-EFAA33A0AD0D | 70LY | HD 38858 |   | @829037 | Gaia DR2 3023711269067191296\|P | Orion | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
another


D1CC3E1B-D4B2-CF47-B9BE-504CAB5E89C8 | 70LY | UCAC3 281-150921 |   | @233784 | Gaia DR2 2135110259540829824\|K | Cygnus | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
another 

98487FD6-3437-0C4B-858A-7CA628E0E394 | 70LY | HD 25329 |   | @689029 | Gaia DR2 219057458247921536\|** | Perseus | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
another 

30A524D2-3BF3-2F43-AA4B-96DB8466F07E | 70LY | EGGR 283 |   | @1499736 | Gaia DR2 1884744525522874880\|W | Pegasus | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
614FE6A2-84B3-724B-B8B8-953208D41026 | 70LY | G 220-6 |   | @136498 | Gaia DR2 455808803070744832 | Perseus | 0 | 0 |   | Simbad\|GaiaDR2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ljramones** [comment]
that is all I found

**Comment by BoatrightTBC** [comment]
ooops.  I'll fix the data too tho, so when people are looking at it, it's not wrong.

Ooops.

________________________________

**Comment by ljramones** [comment]
for 0 rather than O, I make the change because I figure it is a reasonable finger issue

**Comment by ljramones** [comment]
as soon as I have an updated excel/csv file, I will retest and close

**Comment by BoatrightTBC** [comment]
Updated 70 and 270 xlsx files in https://tbcsoftware.com/trips/Datasets/

________________________________

**Comment by ljramones** [comment]
I think I sorted out the issues with spectral classes. I made modifications to the 270 ly file to fix issues in it.

**Comment by BoatrightTBC** [comment]
I need your copy of the file so I can use it as the base for things as I move forward.

________________________________

**Comment by ljramones** [comment]
Sure, I finished all the items I wanted to for v0.6.7.

There are about 15 items fixed and/or added.

I’ll do a test and release tonight.

Then I guess, I’ll wanted for more feedback

I’ll send you that file
