### ISSUE TITLE
bringing up search query before setting a data context will throw a null pointer exception

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#44]
Once a data context is set, it is ok, but if a context is not set, then 

its thrown here:
        d2EarthSlider = new DistanceSelectionPanel(query.getAstroSearchQuery().getDistanceFromCenterStar(),dataSetContext.getDescriptor().getDistanceRange());

Caused by: java.lang.NullPointerException
	at com.teamgannon.trips.search.SearchPane.<init>(SearchPane.java:41)
	at com.teamgannon.trips.dialogs.query.QueryDialog.<init>(QueryDialog.java:39)
	at com.teamgannon.trips.controller.MainPane.runQuery(MainPane.java:542)
	... 52 more

**Comment by ljramones** [comment]
fixed
