### ISSUE TITLE
routing issue reported by GH Metz

### ISSUE THREAD

**Issue by ljramones** [ljramones/trips#80]
First, the route is still there in the side panel under Star Routing, but I was no longer seeing the actual route visibly in the 3D area... until I clicked off showing labels, then it came back. Turning labels back on did not remove it again, I think it's just a matter of forcing a redraw of the 3D area. (Route is Delta Pavonis > Sigma Draconis > Groombridge 1618 if that matters, but I suspect it wouldn't.) So the route is there.
Next, after the route was in place, I went to General and clicked "Plot Routes", which is where the error happened. I've included the Exception info from the terminal; it mentions "... 53 more" at the end, but when I check the log folder the error isn't listed there. Also included is the best guess of where I started the route - there's a couple of clicks registered prior to that but they were looking at system information (aka "trying to figure out what I was doing"). That's in the attached text file.
Do let me know if you want this written up as an issue on GitHub and I'll do that.

--------------- 

2020-09-14 07:59:09.764  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : Primary button pressed
2020-09-14 07:59:35.973  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RouteManager  : Start charting the route:RouteDescriptor(name=TEst1, maxLength=0.0, color=0xff6666ff, routeList=[], startStar=Delta Pavonis, routeNotes=testing, lineSegments=[])
2020-09-14 07:59:52.683  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : mouse click detected! StarDisplayRecord(recordId=d5e732c8-d808-4355-a664-c35740ec09cb, dataSetName=100LY, starName=Sigma Draconis, starColor=0xff9833ff, radius=0.83, distance=18.81, spectralClass=K0V, actualCoordinates=[2.56, -6.01, 17.64], coordinates=Point3D [x = 47.20173535791758, y = -110.81344902386118, z = 325.2494577006508], notes=initial load of object for CHView file)
2020-09-14 07:59:52.819  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : Primary button pressed
2020-09-14 07:59:55.679  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RouteManager  : route continued
2020-09-14 07:59:55.679  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RouteManager  : Next Routing step:RouteDescriptor(name=TEst1, maxLength=0.0, color=0xff6666ff, routeList=[7afb3c42-f896-43c1-8cea-3149962c3288, d5e732c8-d808-4355-a664-c35740ec09cb], startStar=Delta Pavonis, routeNotes=testing, lineSegments=[Point3D [x = 78.91540130151846, y = -125.56399132321043, z = -335.943600867679], Point3D [x = 47.20173535791758, y = -110.81344902386118, z = 325.2494577006508]])
2020-09-14 08:00:06.712  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : mouse click detected! StarDisplayRecord(recordId=66a46dc5-0386-48ec-8701-865b15d06f14, dataSetName=100LY, starName=Groombridge 1618, starColor=0xff9833ff, radius=0.83, distance=15.89, spectralClass=K7Ve, actualCoordinates=[-9.19, 4.72, 12.08], coordinates=Point3D [x = -169.44685466377442, y = 87.02819956616052, z = 222.73318872017356], notes=initial load of object for CHView file)
2020-09-14 08:00:06.838  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : Primary button pressed
2020-09-14 08:00:09.638  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RouteManager  : route continued
2020-09-14 08:00:09.639  INFO 6492 --- [lication Thread] c.teamgannon.trips.controller.MainPane   : new route
2020-09-14 08:00:09.666  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RoutingPanel  : adding routes
2020-09-14 08:00:09.670  INFO 6492 --- [lication Thread] com.teamgannon.trips.routing.RouteCell   : show route:Route: 1: TEst1 has 2 segments
2020-09-14 08:00:09.671  INFO 6492 --- [lication Thread] com.teamgannon.trips.routing.RouteCell   : show route:Route: 1: TEst1 has 2 segments
2020-09-14 08:00:17.969  INFO 6492 --- [lication Thread] com.teamgannon.trips.routing.RouteCell   : show route:Route: 1: TEst1 has 2 segments
2020-09-14 08:00:39.280  INFO 6492 --- [lication Thread] com.teamgannon.trips.service.Simulator   : clearing stars
2020-09-14 08:00:39.281  INFO 6492 --- [lication Thread] com.teamgannon.trips.service.Simulator   : drawing 25 random stars, plus earth
2020-09-14 08:00:39.282  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : sol is at [0.0, 0.0, 0.0]
2020-09-14 08:01:20.094  INFO 6492 --- [lication Thread] c.teamgannon.trips.controller.MainPane   : DB Query returns 85 stars
2020-09-14 08:01:20.102  INFO 6492 --- [lication Thread] c.t.trips.graphics.AstrographicPlotter   : New Plot Scaling parameters:ScalingParameters(scalingFactor=18.438177874186554, minX=-17.45, maxX=19.43, minY=-18.01, maxY=18.38, minZ=-18.22, maxZ=17.64, gridScale=67.09652928416487, scaleIncrement=5.0)
2020-09-14 08:01:20.103  INFO 6492 --- [lication Thread] c.t.trips.graphics.GridPlotManager       : rebuilding grid scale increment: 5.0
2020-09-14 08:01:20.105  INFO 6492 --- [lication Thread] c.t.trips.graphics.GridPlotManager       : show scale
2020-09-14 08:01:20.129  INFO 6492 --- [lication Thread] c.t.t.g.panes.InterstellarSpacePane      : sol is at [0.0, 0.0, 0.0]
2020-09-14 08:01:20.132  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RouteManager  : Plot done
2020-09-14 08:01:22.271  INFO 6492 --- [lication Thread] c.teamgannon.trips.support.AlertFactory  : 85 records plotted from dataset 100LY.
2020-09-14 08:01:22.272  INFO 6492 --- [lication Thread] com.teamgannon.trips.routing.RouteCell   : show route:Route: 1: TEst1 has 2 segments
2020-09-14 08:01:22.272  INFO 6492 --- [lication Thread] c.teamgannon.trips.routing.RoutingPanel  : adding routes
2020-09-14 08:01:22.274  INFO 6492 --- [lication Thread] com.teamgannon.trips.routing.RouteCell   : show route:Route: 1: TEst1 has 2 segments
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
        at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
        at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
        at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1885)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
        at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
        at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
        at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
        ... 42 more
Caused by: java.lang.NullPointerException
        at com.teamgannon.trips.routing.RouteManager.plotRoutes(RouteManager.java:253)
        at com.teamgannon.trips.graphics.panes.InterstellarSpacePane.plotRoutes(InterstellarSpacePane.java:363)
        at com.teamgannon.trips.controller.MainPane.plotRoutes(MainPane.java:576)
        ... 53 more

**Comment by ljramones** [comment]
I tested this and could not reproduce.
I may have fixed whatever was the underlying issue
